// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news.proto

package com.example.grpcserver.news.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:news.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
