// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news.proto

package com.example.grpcclient.news.proto;

public interface MyMemberRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:news.MyMemberRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>bool isMember = 3;</code>
   * @return The isMember.
   */
  boolean getIsMember();
}
