// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news.proto

package com.example.grpcclient.news.proto;

public final class NewsProto {
  private NewsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_MyMemberRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_MyMemberRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_ErrorInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_ErrorInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnews.proto\022\004news\">\n\017MyMemberRequest\022\014\n" +
      "\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\r\022\020\n\010isMember\030\003 \001" +
      "(\010\"\035\n\nMyResponse\022\017\n\007message\030\001 \001(\t\"2\n\tErr" +
      "orInfo\022\021\n\terrorCode\030\001 \001(\t\022\022\n\ndefaultMsg\030" +
      "\002 \001(\t2\221\002\n\tMyService\022>\n\021sendMessageSingle" +
      "\022\025.news.MyMemberRequest\032\020.news.MyRespons" +
      "e\"\000\022@\n\021sendMessageServer\022\025.news.MyMember" +
      "Request\032\020.news.MyResponse\"\0000\001\022@\n\021sendMes" +
      "sageClient\022\025.news.MyMemberRequest\032\020.news" +
      ".MyResponse\"\000(\001\022@\n\017sendMessageBoth\022\025.new" +
      "s.MyMemberRequest\032\020.news.MyResponse\"\000(\0010" +
      "\001B0\n!com.example.grpcclient.news.protoB\t" +
      "NewsProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_news_MyMemberRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_news_MyMemberRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_MyMemberRequest_descriptor,
        new java.lang.String[] { "Name", "Age", "IsMember", });
    internal_static_news_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_news_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_MyResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_news_ErrorInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_news_ErrorInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_ErrorInfo_descriptor,
        new java.lang.String[] { "ErrorCode", "DefaultMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
